"""final models

Revision ID: 7e21bc2f323f
Revises: eb8eef6c0b67
Create Date: 2026-04-15 19:24:21.870017

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e21bc2f323f'
down_revision: Union[str, Sequence[str], None] = 'eb8eef6c0b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    # Ніяких drop_table / drop_index тут більше немає
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted ###
    # Нічого не відновлюємо, бо ця ревізія лише маркер
    pass
    # ### end Alembic commands ###
